#!/usr/bin/env bash
# print subdomain name, record-type and IP pointer Address.

domain=$1

# ********* displayALL() function **************
function displayAll() {
    for arg;
    do
	echo -n "The subdomain $arg is a "
	dig "$arg"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
    done
}

# ********** MAIN PROGRAM **********************

if [ "$1" ];
then
    displayAll 'www' 'lb-01' 'web-01' 'web-02'
fi
