#!/usr/bin/env bash
# This scripts installs nginx in a new ubuntu machine.                                               
sudo apt update
sudo -y apt-get install curl
sudo -y apt-get install nginx
sudo ufw allow 'Nginx Full'
sudo service nginx start
echo 'Holberton School' > /var/www/html/index.html
