#!/usr/bin/env bash
# This scripts installs nginx in a new ubuntu machine.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html
