#!/usr/bin/env bash
# nginex redirection /redirect_me
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' ~/etc/nginx/sites-available/default
