#!/usr/bin/env bash
# a Bash script that loops from 1 to 10.
counter=1
while ((counter <= 10))	
do
	if ((counter == 4))
	then
		echo "bad luck"
	elif ((counter == 8))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((counter++))
done
