#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes.
hour=0
minutes=1
while ((hour <= 12))
	do
	echo "Hour: $hour"
	while ((minutes < 60))	
	do
		echo "$minutes"
		((minutes++))
	done
	((minutes = 1))
	((hour++))
done