#!/usr/bin/env bash
# Configures NGINX to run as nginx user (not root).

# 1. Kill nginx process (neccesary).
pkill nginx

# 2. Change NGINX permissions on the config files.
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

# 3. Have NGINX listen on port 8080.
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

# 4. initiate nginx service as 'nginx' user.
sudo -u nginx service nginx start
